Change exit error codes to use sysexits.h values

diff --git a/rarch b/rarch
--- a/rarch
+++ b/rarch
@@ -1,8 +1,8 @@
 #!/bin/bash
 # ==================================================================================================
 # 
-# rarch 2.0 - create encrypted TAR archives from directories
-# Copyright (C) 2017 Rui Carlos Gonçalves
+# rarch 2.1 - create encrypted TAR archives from directories
+# Copyright (C) 2015-2017 Rui Carlos Gonçalves
 # 
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -21,8 +21,9 @@
 # ==================================================================================================
 #
 # Author:       Rui Carlos Gonçalves <rcgoncalves.pt@gmail.com>
-# Version:      2.0
-# Date:         August 26, 2017
+# Version:      2.1
+# Date:         August 27, 2017
+# License:      GNU GPL v2
 #
 # ==================================================================================================
 #
@@ -34,11 +35,16 @@
 #
 # Change Log
 #
+# Version 2.1
+#   2017-08-27
+#     * Change exit error codes to use sysexits.h values.
+#
 # Version 2.0
 #   2017-08-26
 #     * Change script to use TAR and GnuPG instead of hdiutil.
 #     * Make use of date in file name optional.
 #     * Improve robustness of the script.
+#
 # Version 1.0
 #   2015-08-01
 #     * First version.
@@ -47,42 +53,64 @@
 
 set -u
 
-# Returns the absolute path of a given directory path
-get_absolute_path() {
-    if [[ -d "$1" ]]; then
-        echo "$(cd "$1" && pwd)"
+# Error exit codes.
+readonly EX_USAGE=64
+readonly EX_DATAERR=65
+readonly EX_UNAVAILABLE=69
+readonly EX_SOFTWARE=70
+readonly EX_CANTCREAT=73
+readonly EX_IOERR=74
+
+# Prints to the STDOUT the absolute path of a given directory path.
+# Params:
+# * a directory path (possibly relative to current location).
+# Returns:
+# * EX_USAGE if the number of arguments is wrong.
+# * EX_DATAERR if the path is not a directory.
+# * 0 otherwise.
+get_absolute_dir_path() {
+    [[ "$#" -eq 1 ]] || return "$EX_USAGE"
+    local path="$1"
+    if [[ -d "$path" ]]; then
+        echo "$(cd "$path" && pwd)"
         return 0
     else
-        return 1
+        return "$EX_DATAERR"
     fi
 }
 
 # ==================================================================================================
 
+# Script name.
 readonly NAME='rarch'
-readonly VERSION='2.0'
+# Script version.
+readonly VERSION='2.1'
+# Script year.
 readonly YEAR='2017'
 
 print_version() {
-    echo -e "$NAME $VERSION, Copyright (C) $YEAR Rui Carlos Goncalves"
+    echo "$NAME $VERSION, Copyright (C) $YEAR Rui Carlos Goncalves"
 }
 
 print_help() {
     print_version
     echo "Create encrypted TAR archives from directories using GnuPG, with a public key"
-    echo "specified.  An output file is created for each input directory. Optionally it"
-    echo "can append the current date to the created TAR archive, so that the archive"
+    echo "specified.  An output file is created for each input directory.  Optionally it"
+    echo "can append the current date to the created TAR archive,  so that the archive"
     echo "creation date can be known after decrypting the file."
     echo ""
     echo "Usage:"
     echo "    $NAME [options] [directories]"
     echo ""
     echo "Options:"
-    echo "    -k USER-ID user ID of the GnuPG public key for encrypting the archive"
+    echo "    -r USER-ID user ID of the GnuPG public key for encrypting the archive"
     echo "    -d         append current date to TAR archive (format YYYYMMDD)"
-    echo "    -v         print the program version and exit"
+    echo "    -v         print the script version and exit"
     echo "    -h         print this help message and exit"
     echo ""
+    echo "Return values:"
+    echo "    The script returns 0 if no error occurred.  In case of error it returns an"
+    echo "    error exit code based on sysexits.h."
     echo ""
     echo "$NAME comes with ABSOLUTELY NO WARRANTY.  This is free software, and"
     echo "you are welcome to redistribute it under certain conditions.  See the GNU"
@@ -91,12 +119,11 @@ print_help() {
 
 # ==================================================================================================
 
-DIR=''
 DATE=''
 KEY=''
-while getopts 'k:dvh' FLAG; do
+while getopts 'r:dvh' FLAG; do
     case "$FLAG" in
-        k)
+        r)
             KEY="$OPTARG"
             ;;
         d)
@@ -113,89 +140,91 @@ while getopts 'k:dvh' FLAG; do
         \?)
             echo ""
             print_help
-            exit 1
+            exit "$EX_USAGE"
             ;;
     esac
 done
-readonly DIR
 readonly DATE
 readonly KEY
 
-shift $((OPTIND-1))
+
+shift "$((OPTIND-1))"
 if [[ "$#" -eq 0 ]]; then
     echo "$NAME: no input directories specified" >&2
     echo ""
     print_help
-    exit 1
+    exit "$EX_USAGE"
 fi
 
 if ! hash gpg; then
     echo "$NAME: 'gpg' not available (required)" >&2
-    exit 1
+    exit "$EX_UNAVAILABLE"
 fi
 if ! hash base64; then
     echo "$NAME: 'base64' not available (required)" >&2
-    exit 1
+    exit "$EX_UNAVAILABLE"
 fi
 
-
+# Exit code associated with the latest error (used as the script exit code).
 error=0
 
-readonly CURR_PATH="$(pwd)"
-# define a random temporary path in current working directory
-# it will be used to place the temporary TAR archives
-readonly TMP_PATH="$CURR_PATH/TMP.$(date | gpg --print-md MD5 | tr -s ' ' | base64)"
-# stores the latest used path used for temporary TAR archive (the one we still may have to delete)
-tar_path=''
-# setup a trap to cleanup temporary files
+
+readonly WORKDIR="$(pwd)"
+# Define a random temporary path in current working directory.
+# It will be used to place the temporary TAR archives.
+readonly TMP="$WORKDIR/TMP.$(date | gpg --print-md MD5 | tr -s ' ' | base64)"
+# Stores the latest used path used for temporary TAR archive (the one we still may have to delete).
+tar=''
+# Setup a trap to cleanup temporary files.
 cleanup() {
-    [[ "$(dirname "$tar_path")" == "$TMP_PATH" ]] && [[ -f "$tar_path" ]] && rm "$tar_path"
-    [[ -d "$TMP_PATH" ]] && rmdir "$TMP_PATH"
+    [[ "$(dirname "$tar")" == "$TMP" ]] && [[ -f "$tar" ]] && rm "$tar"
+    [[ -d "$TMP" ]] && rmdir "$TMP"
 }
 trap cleanup EXIT SIGINT SIGTERM SIGQUIT
-# assumes the current directory is valid
-mkdir $TMP_PATH >/dev/null 2>&1
+# Assumes the current directory is valid!
+mkdir "$TMP" >/dev/null 2>&1
 if [[ "$?" -ne 0 ]]; then
     echo "$NAME: error creating archives" >&2
-    exit 1
+    exit "$EX_IOERR"
 fi
 
 
 for dir in "$@"; do
     if [[ "$dir" == "/" ]]; then
-        echo "$NAME: cannot process the root directory (skipping directory)." >&2
-        let error++
+        echo "$NAME: cannot process the root directory (skipping directory)" >&2
+        error="$EX_DATAERR"
     elif [ ! -d "$dir" ]; then
-        echo "$NAME: '$dir' is not a valid directory (skipping directory)." >&2
-        let error++
+        echo "$NAME: '$dir' is not a valid directory (skipping directory)" >&2
+        error="$EX_DATAERR"
     else
-        abs_path="$(get_absolute_path "$dir")"
-        base_name="$(basename "$abs_path")"
-        dir_name="$(dirname "$abs_path")"
-        tar_path="$TMP_PATH/$base_name$DATE.tar"
-        gpg_path="$CURR_PATH/$base_name.gpg"
+        abs="$(get_absolute_dir_path "$dir")"
+        base="$(basename "$abs")"
+        dir="$(dirname "$abs")"
+        tar="$TMP/$base$DATE.tar"
+        gpg="$WORKDIR/$base.gpg"
 
-        if [[ -e "$gpg_path" ]]; then
-            echo "$NAME: output file '$gpg_path' already exists (skipping directory)" >&2
-            let error++
+        if [[ -e "$gpg" ]]; then
+            echo "$NAME: output file '$gpg' already exists (skipping directory)" >&2
+            error="$EX_CANTCREAT"
         else
-            tar cf "$tar_path" -C "$dir_name" "$base_name"
+            tar cf "$tar" -C "$dir" "$base"
             if [[ "$?" -eq 0 ]]; then
                 if [[ -z "$KEY" ]]; then
-                    gpg --encrypt --out "$gpg_path" $tar_path
+                    gpg --quiet --encrypt --out "$gpg" "$tar"
                 else
-                    gpg --encrypt -r "$KEY" --out "$gpg_path" $tar_path
+                    gpg --quiet --encrypt --recipient "$KEY" --output "$gpg" "$tar"
                 fi
                 if [[ "$?" -ne 0 ]]; then
                     echo "$NAME: error encrypting archive" >&2
+                    error="$EX_SOFTWARE"
                 fi
             else
                 echo "$NAME: error creating archive" >&2
-                let error++
+                error="$EX_IOERR"
             fi
-            [[ -f "$tar_path" ]] && rm "$tar_path"
+            [[ -f "$tar" ]] && rm "$tar"
         fi
     fi
 done
 
-exit $error
+exit "$error"
